MODULE_NAME="bookstack"
MODULE_DESCRIPTION="Knowledge Base / Wiki (mit MariaDB)"
MODULE_SERVICES="bookstack-db bookstack"
MODULE_DATA_DIRS="data/bookstack-db data/bookstack"
MODULE_DEPENDS=""
MODULE_CONFLICTS=""
MODULE_GPU_SUPPORT=""
MODULE_PORT="8875"
MODULE_INTERNAL_PORT="80"
MODULE_DOMAIN_VAR="BOOKSTACK_DOMAIN"
MODULE_DB=""
MODULE_SSO_TYPE="oauth2"
MODULE_SSO_GROUP="standard-users"
